# Generated by Django 4.2.30 on 2026-10-07 15:10

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Endpoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "site_id",
                    models.PositiveIntegerField(blank=True, db_index=True, null=True),
                ),
                ("app_label", models.CharField(db_index=True, max_length=64)),
                ("route_name", models.CharField(max_length=160)),
                ("method", models.CharField(max_length=8)),
                ("deprecated", models.BooleanField(default=False)),
                ("sunset_date", models.DateField(blank=True, null=True)),
                ("replacement", models.CharField(blank=True, max_length=160)),
                ("owner", models.CharField(blank=True, max_length=160)),
                ("notes", models.TextField(blank=True)),
            ],
            options={
                "ordering": ("app_label", "route_name", "method"),
                "unique_together": {("site_id", "app_label", "route_name", "method")},
            },
        ),
        migrations.CreateModel(
            name="Consumer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("api_key", "API key"),
                            ("user", "User"),
                            ("ip_hash", "IP hash"),
                        ],
                        max_length=16,
                    ),
                ),
                ("ref_hash", models.CharField(db_index=True, max_length=64)),
                ("user_agent_family", models.CharField(blank=True, max_length=64)),
                ("first_seen", models.DateTimeField(default=django.utils.timezone.now)),
                ("last_seen", models.DateTimeField(default=django.utils.timezone.now)),
                ("request_count", models.PositiveIntegerField(default=0)),
                ("contact", models.CharField(blank=True, max_length=200)),
                ("notes", models.TextField(blank=True)),
            ],
            options={
                "ordering": ("-last_seen",),
                "unique_together": {("kind", "ref_hash")},
            },
        ),
        migrations.CreateModel(
            name="EndpointStat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(db_index=True)),
                ("client_type", models.CharField(default="anon", max_length=16)),
                ("status_class", models.CharField(default="2xx", max_length=4)),
                ("count", models.PositiveIntegerField(default=0)),
                (
                    "endpoint",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stats",
                        to="django_api_usage.endpoint",
                    ),
                ),
            ],
            options={
                "ordering": ("-date",),
                "indexes": [
                    models.Index(
                        fields=["date", "endpoint"], name="django_api__date_fd01a8_idx"
                    )
                ],
                "unique_together": {
                    ("endpoint", "date", "client_type", "status_class")
                },
            },
        ),
    ]
