# Generated by Django 4.2.30 on 2026-10-08 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_api_usage", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="endpoint",
            name="route_path",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
