# Generated by Django 4.2.30 on 2026-10-08 11:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("django_api_usage", "0002_endpoint_route_path"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="endpointstat",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="endpointstat",
            name="client_app",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterUniqueTogether(
            name="endpointstat",
            unique_together={
                ("endpoint", "date", "client_type", "client_app", "status_class")
            },
        ),
        migrations.CreateModel(
            name="ClientApp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="Short, stable label stored in the counters (e.g. 'mugikorra').",
                        max_length=64,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=160)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "priority",
                    models.PositiveSmallIntegerField(
                        default=100,
                        help_text="Lower wins when several apps could match.",
                    ),
                ),
                (
                    "domains",
                    models.TextField(
                        blank=True,
                        help_text="One host per line; matched against the Origin/Referer host.",
                    ),
                ),
                (
                    "ip_networks",
                    models.TextField(
                        blank=True, help_text="One CIDR per line, e.g. 10.0.0.0/8."
                    ),
                ),
                (
                    "user_agent_patterns",
                    models.TextField(
                        blank=True,
                        help_text="One substring per line, matched case-insensitively.",
                    ),
                ),
                (
                    "accounts",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Users (and therefore DRF tokens) that belong to this app.",
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Client application",
                "verbose_name_plural": "Client applications",
                "ordering": ("priority", "slug"),
            },
        ),
    ]
