# Generated by Django 4.2.30 on 2026-10-08 12:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def accounts_to_rows(apps, schema_editor):
    """Keep the assignments made through the removed many-to-many field.

    ``ClientApp.accounts`` (0003) held every assigned account in a join table.
    It was replaced by one row per account, which the resolver can read with a
    single indexed lookup instead of loading the whole list into memory.
    """
    ClientApp = apps.get_model("django_api_usage", "ClientApp")
    ClientAppAccount = apps.get_model("django_api_usage", "ClientAppAccount")

    rows = [
        ClientAppAccount(client_app_id=app.pk, user_id=user_id)
        for app in ClientApp.objects.all()
        for user_id in app.accounts.values_list("pk", flat=True)
    ]
    ClientAppAccount.objects.bulk_create(rows, ignore_conflicts=True)


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("django_api_usage", "0003_alter_endpointstat_unique_together_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClientAppAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("notes", models.CharField(blank=True, max_length=200)),
                (
                    "client_app",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="accounts",
                        to="django_api_usage.clientapp",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        help_text="One application per account, so the token is unambiguous.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="api_usage_client_app",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Account",
                    ),
                ),
            ],
            options={
                "verbose_name": "Client application account",
                "verbose_name_plural": "Client application accounts",
                "ordering": ("client_app", "user"),
            },
        ),
        migrations.RunPython(accounts_to_rows, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="clientapp",
            name="accounts",
        ),
    ]
